# Test build your arduino libraries with travis and the official arduino tool chain

# assumes directory structure
# /NullStream
#   NullStream.h
#   NullStream.cpp
#   examples
#     NullStreamExample
#       NullStreamExample.ino

language: cpp
env:
 # We'll test against only a single library example, and only for uno, but you could add more combinations
 # https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc
 - BOARD=arduino:avr:uno NAME=GSMUserButtonAndLEDTest

compiler:
 - gcc

before_install:
 - sudo apt-get update -qq && sudo apt-get install -qq openjdk-7-jre avr-libc gcc-avr xvfb

install:
 # arduino
 - wget http://downloads-02.arduino.cc/arduino-1.6.5-linux64.tar.xz
 - tar -xvf arduino-1.6.5-linux64.tar.xz
 - sudo mv arduino-1.6.5/ /usr/local/share/arduino

before_script:
 # arduino requires an X server even with command line
 # https://github.com/arduino/Arduino/issues/1981
 - Xvfb :1 -screen 0 1024x768x16 &> xvfb.log &
 # put your source files in a folder under a new libraries folder
 - sudo mkdir /usr/src/arduino
 - sudo mkdir /usr/src/arduino/libraries
 - sudo ln -s $TRAVIS_BUILD_DIR /usr/src/arduino/libraries/gsm-playground

script:
 - sudo DISPLAY=:1.0 /usr/local/share/arduino/arduino --board $BOARD --pref sketchbook.path=/usr/src/arduino --verify /usr/src/arduino/libraries/gsm-playground/examples/$NAME/$NAME.ino
